name: Print OIDC JWT

on:
  workflow_dispatch:

permissions:
  id-token: write   # 👈 REQUIRED
  contents: read

jobs:
  show-jwt:
    runs-on: ubuntu-latest

    steps:
      - name: Get OIDC token
        id: oidc
        run: |
          TOKEN=$(curl -s \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=example")

          echo $TOKEN | base64
          echo "JWT=$(echo $TOKEN | base64)"
